CODE_GRIS = 0
CODE_AMARILLO = 1
CODE_AZUL = 2
CODE_CELESTE = 3
CODE_MORADO = 4
CODE_NARANJA = 5
CODE_ROJO = 6
CODE_VERDE = 7

COLORES_CHOICES = (
		(CODE_GRIS, 'gris'),
		(CODE_AMARILLO, 'amarillo'),
		(CODE_AZUL, 'azul'),
		(CODE_CELESTE, 'celeste'),
		(CODE_MORADO, 'morado'),
		(CODE_NARANJA, 'naranja'),
		(CODE_ROJO, 'rojo'),
		(CODE_VERDE, 'verde'),
)

COLORES_DICT = {}
COLORES_DICT[CODE_GRIS] = 'gris'
COLORES_DICT[CODE_AMARILLO] = 'amarillo'
COLORES_DICT[CODE_AZUL] = 'azul'
COLORES_DICT[CODE_CELESTE] = 'celeste'
COLORES_DICT[CODE_MORADO] = 'morado'
COLORES_DICT[CODE_NARANJA] = 'naranja'
COLORES_DICT[CODE_ROJO] = 'rojo'
COLORES_DICT[CODE_VERDE] = 'verde'